### ISSUE TITLE
c4_api Handshake failed

### ISSUE THREAD

**Issue by parashu-rama** [itseccode/c4_tools#1]
Добрый день!

Нужно установить libcurl4-openssl-dev, иначе:

/usr/local/bin/c4_api -u admin_01:pass_01 --ip 10.123.10.11 print_cgws
Traceback (most recent call last):
  File "/usr/local/bin/c4_api", line 33, in <module>
    sys.exit(load_entry_point('c4-api==1.1', 'console_scripts', 'c4_api')())
  File "/usr/local/lib/python3.10/dist-packages/c4_api-1.1-py3.10.egg/c4_api/__init__.py", line 347, in cli
    api.print_cgws()
  File "/usr/local/lib/python3.10/dist-packages/c4_api-1.1-py3.10.egg/c4_api/__init__.py", line 183, in print_cgws
    master_uuid = self.__get_master_uuid()
  File "/usr/local/lib/python3.10/dist-packages/c4_api-1.1-py3.10.egg/c4_api/__init__.py", line 60, in __get_master_uuid
    c.perform()
pycurl.error: (35, 'gnutls_handshake() failed: Handshake failed')

**Comment by itseccode** [comment]
Необходимость установки была в ранней версии утилиты. Сейчас `c4_api` заменена на `c4_lib`. При установке чекаются зависимости и доставляются необходимые компоненты (разумеется, кроме OpenSSL). Рекомендую взять свежие версии инструментов.
